# Generated by Django 4.2.2 on 2023-06-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snapshotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SERVER_INDEX', models.IntegerField()),
                ('CLIENT_INDEX', models.IntegerField()),
                ('SCORE', models.IntegerField()),
                ('MODIFIED', models.DateTimeField(verbose_name='timeout')),
            ],
        ),
    ]
